export const CADASTRO_SUCESS = 'CADASTRO_SUCESS';
export const CADASTRO_REQUEST = 'CADASTRO_REQUEST';
export const CADASTRO_FAILURE = 'CADASTRO_FAILURE';

export const LOGIN_SUCESS = 'LOGIN_SUCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';

export const CHANGE_LETTER = 'CHANGE_LETTER';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHILD_LETTER = 'CHILD_LETTER';
